[features]
seeds = false
skip-lint = false
[programs.localnet]
solanapdas = "Ay7HC7KkZyXawNsZ2PQX9Z4o4Pte8qCTbLJQQXJnm3qv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/usuario1/my-solana-wallet/my-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
